### ISSUE TITLE
MalformedPolicyDocument issue

### ISSUE THREAD

**Issue by chenrui333** [clowdhaus/terraform-aws-rds-proxy#8]
**Describe the bug**

Running into the issue when creating the IAM role
```
│ Error: Error putting IAM role policy chapstick-rds-proxy: MalformedPolicyDocument: Resource  must be in ARN format or "*".
│ 	status code: 400, request id: 2cd81d3c-374c-4b97-9243-96eda3afb0db
│
│   with module.chapstick_rds_proxy.aws_iam_role_policy.this[0],
│   on .terraform/modules/chapstick_rds_proxy/main.tf line 176, in resource "aws_iam_role_policy" "this":
│  176: resource "aws_iam_role_policy" "this" {
```

**To Reproduce**
1. use the default example to create the proxy

**Comment by bryantbiggs** [comment]
hi @chenrui333 - which example gave you the issue? I've just re-ran the `postgresql_iam_cluster` and `postgresql_iam_instance` and both launch without issue as they are defined in the project

**Comment by chenrui333** [comment]
Yeah, after switching to use the full example, it works fine for me. Previously I was using the secretmanager key I created in the other place.

**Comment by chenrui333** [comment]
Thanks! Closing the issue now.

**Comment by chenrui333** [comment]
@bryantbiggs I have another question, why do I need to have both db_host and db_name? Isn't aurora target cluster enough? (the `db_host` seems pretty unnecessary as the connection can be used for talking to different databases?)

**Comment by chenrui333** [comment]
After working with the AWS RDS support, I found the secret setup probably has some issue, we ended up re-creating the RDS secret for RDS proxy

**Comment by bryantbiggs** [comment]
ah, you are correct @chenrui333 - my linting checks seemed to have been failing me. you do not need either `db_host` or `db_name` - I just pushed a patch to remove these as they were unused in the codebase (probably an artifact of an earlier refactoring when additional/custom endpoints came out). thanks for catching that!
